# Routeur uniquement
if ($fromhost-ip == '192.168.5.1') then {

    # Critique
    if ($syslogseverity <= 2) then {
        action(type="omfile" file="/var/log/tplink-critical.log")
    }

    # Erreurs
    if ($syslogseverity == 3) then {
        action(type="omfile" file="/var/log/tplink-error.log")
    }

    # Info / normal
    if ($syslogseverity >= 5) then {
        action(type="omfile" file="/var/log/tplink-info.log")
    }

    stop
}